# Generated by Django 4.2.7 on 2025-12-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget_app', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
