# Generated by Django 5.1.7 on 2025-12-22 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget_app', '0005_joinrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='joinrequest',
            name='unique_family_user_join_request',
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('family', 'user')},
        ),
    ]
